### ISSUE TITLE
Updating theme asks for GH API key

### ISSUE THREAD

**Issue by eku** [RocketRobz/TWiLightMenu-Updater#103]
It is no longer possible to update themes with this software. It asks for an API key for Github. What should you enter?

**Comment by SuperSaiyajinStackZ** [comment]
That mainly means, you reached the GitHub API ratelimit afaik. Just wait for a while or enter your GitHub account data.

**Comment by eku** [comment]
> That mainly means, you reached the GitHub API ratelimit

With one request? With respect, but that doesn't seem like a plausible explanation.

**Comment by RocketRobz** [comment]
> With one request? With respect, but that doesn't seem like a plausible explanation.

How come?

**Comment by RocketRobz** [comment]
Closing, because this cannot be worked around.
