### ISSUE TITLE
Feature Request: Update UI/Progress Bar

### ISSUE THREAD

**Issue by iTNZPP** [RocketRobz/TWiLightMenu-Updater#37]
Please add a updated UI saying the versions of TWLMenu++ and nds-bootstrap. And please a add a progress bar for downloading updates/boxart and cheats. Thanks.

**Comment by JeodC** [comment]
Pseudocode for a "progress bar":

[SCANNING]
Count the number of directories to be scanned
Using fractions, output the progress (x/y) (i.e. below)

Scanning directories...(3/14)

[DOWNLOADING]
Similar principle, but instead count the number of .nds files scanned

**Comment by JeodC** [comment]
Pseudocode for Versions UI:

in main.cpp, under the following:
`const char *row_titles2[] = {
	"TWL Menu++",
	"nds-bootstrap",
	"Updater",
	"Downloads",
};`
add smallfont CurrentVersion=[major.minor.micro] and get this information from release_bootstrap.ver (TWL++ has no .ver file currently)

**Comment by Epicpkmn11** [comment]
#57 Semi fixes this, it adds text so you know something's happening, but it's not a real progress bar or even [things done] / [total], just [things done], so this should probably stay open.

**Comment by SuperSaiyajinStackZ** [comment]
https://github.com/RocketRobz/TWiLightMenu-Updater/commit/b3c83055aa41deb0a198bd4f6e96f56bca1480ef Should add a visual progressbar for downloading, installing and extracting. So the "semi" fix should be fully done now from above.
