### ISSUE TITLE
Downloading Italian boxart fails

### ISSUE THREAD

**Issue by DMSalesman** [RocketRobz/TWiLightMenu-Updater#38]
The Italian boxart is not being downloaded, because it's not found at `IT/<tid>.bmp`, but at `EN/<tid>.bmp`.

By using `YLTI` as an example, downloading `https://art.gametdb.com/ds/coverDS/IT/YLTI.bmp` fails, because the cover is found at `https://art.gametdb.com/ds/coverDS/EN/YLTI.bmp`.

A fallback mechanism might include attempting to download from the `EN`  region if the region derived from the tID doesn't contain the boxart.

**Comment by Intervencion** [comment]
Happens the same with some Spanish roms. EG https://www.gametdb.com/DS/IRES is on EN instead of ES
