### ISSUE TITLE
No Stand By mode?

### ISSUE THREAD

**Issue by xscaralienx** [RocketRobz/TWiLightMenu-Updater#40]
So I noticed after downloading the updater and getting the latest stable (not nightly) version of TWiLight Menu++ through it, that my battery drained extremely fast while closing my 3ds running a DS game when it didn't happened before (battery goes from blue light to red in one single day with the 3DS closed).

Turns out closing my 3ds with TWiLight running no longer starts Stand By mode, as in the light stay solid instead of slowly pulsing, something similar occurs if you play injected GBA games with the 3DS built in VC.

Is this a known issue or a problem for anyone else?

**Comment by RocketRobz** [comment]
Try taking something out of the game card slot, if there's something in it already, then try running the game again.

**Comment by xscaralienx** [comment]
> Try taking something out of the game card slot, if there's something in it already, then try running the game again.

This seems to have fixed it. Any idea if it can be fixed on TWiLight or just something to be on the lookout for?

**Comment by RocketRobz** [comment]
What exactly did you have in the card slot?

**Comment by xscaralienx** [comment]
3DS game. My system is N3DSXL and the game was Pokemon Sun

**Comment by RocketRobz** [comment]
Weird. 3DS carts shouldn't break sleep mode.
Next TWLMenu++ version will have a force sleep mode patch option, so that any card inserted won't break sleep mode.

**Comment by xscaralienx** [comment]
I did tried playing a DS card through TWiLight (I couldn't kept crashing) before noticing the no Stand By mode so that might have started it?
