### ISSUE TITLE
Incorrect currentVersions.ini

### ISSUE THREAD

**Issue by Coder-256** [RocketRobz/TWiLightMenu-Updater#42]
For some reason, the updater always shows a green circle above the "Release" version even though it is fully updated, even after reinstalling from within the updater. Then I realized, here are the contents of my `currentVersions.ini`:

```
[TWILIGHTMENU]
RELEASE = v7.4.1

[NDS-BOOTSTRAP]
RELEASE = v0.17.1
```

There is no section for `TWILIGHTMENU-UPDATER`. I think the issue is that the installed version is set when installing the latest nightly updater:

https://github.com/RocketRobz/TWiLightMenu-Updater/blob/0928f41c31ce6ac75db6d1a444de123f912efd52/source/download.cpp#L726-L733

But for some reason, when installing the latest release updater, it sets the menu version instead:

https://github.com/RocketRobz/TWiLightMenu-Updater/blob/0928f41c31ce6ac75db6d1a444de123f912efd52/source/download.cpp#L749-L753

I haven't tested this, but I think that this actually means that: not only does the updater not write the installed version of the updater, but it actually writes the *latest* version of the menu, even if an older version is installed! This means that both versions in `currentVersions.ini` could be incorrect! (the menu is always shown as updated, even if it isn't; and the updater is always shown as outdated, even if it isn't).

Also, the behavior for the other updater functions is also inconsistent (some only set release, some only set nightly, and some set the wrong thing entirely). I think the best way to fix this is to move all of these changes out of the if blocks. I'll open a PR soon to show what I mean.

**Comment by Epicpkmn11** [comment]
Ah, I wasn't able to test the Updater release while making it as there wasn't a release yet and I guess I forgot to do the right thing for the ini...

The reason nds-bootstrap only sets nightly or release while TWiLight and TWiLight Updater set both (when installing the nightly) is that nds-bootstrap is able to have both the nightly and the release installed at the same time, where TWiLight and the Updater are only able to have one or the other.

**Comment by Coder-256** [comment]
@Epicpkmn11 Thank you, I didn't realize that. There are still some issues though, I'm working on a PR.
