### ISSUE TITLE
[Feature Request] Show changelog before downloading

### ISSUE THREAD

**Issue by DMSalesman** [RocketRobz/TWiLightMenu-Updater#45]
After choosing to update to a stable TWLMenu++, Updater or nds-bootstrap, it would be great if the updater could show the software's changelog, before offering the choice to either proceed with the download or ignore it.

**Comment by Epicpkmn11** [comment]
If you didn't know, you can see the release notes by pressing `Y` or tapping on the green dot.
It'd probably still be nice to have a confirmation screen with them before downloading, though.

**Comment by DMSalesman** [comment]
Thanks for the hint. I'll test it right away.
