### ISSUE TITLE
[Feature Request] Get boxart scan directory from TWL++ settings.ini

### ISSUE THREAD

**Issue by JeodC** [RocketRobz/TWiLightMenu-Updater#46]
Proposed change: When a user selects the boxart button, get the initial directory to scan from /_nds/TWiLightMenu/settings.ini:

[SRLOADER]
ROM_FOLDER=[string]

This is the most likely nds rom directory for the majority of users. After the initial scan, ask for user input for whether to scan additional directories:

Initial scan & download complete! Scan additional directories?
(A: Yes B: No)

**Comment by FlameAlt53** [comment]
so, there's a PR #52 it doesn't read from the ini if I read correctly. But I think that #52 will be good
