### ISSUE TITLE
Feature Request: Ability to update to specific nightlies

### ISSUE THREAD

**Issue by dubbz82** [RocketRobz/TWiLightMenu-Updater#48]
I think it might be useful to be able to update to a specific nightly, since on occasion the latest nightly may have regressions.  This is probably far less important for stable releases.

**Comment by NightYoshi370** [comment]
I don't think this is possible with the way TWLBot is right now. Sorry

**Comment by Epicpkmn11** [comment]
It should be possible, https://api.github.com/repos/TWLBot/Builds/commits has previous commits too
