### ISSUE TITLE
please help im stoopid

### ISSUE THREAD

**Issue by Grendelia** [RocketRobz/TWiLightMenu-Updater#49]
okay so how do i even get to the roms like do i press A i just downloaded it and im updating everything what do i do to play me games?

**Comment by NightYoshi370** [comment]
What?

**Comment by RocketRobz** [comment]
Launch the app, and find the ROMs.
If you get an error saying bootstrap not found, then please download it using the updater.
Also, please don't use the issue tracker for assistance.
