### ISSUE TITLE
[Request] Autodownload box arts

### ISSUE THREAD

**Issue by thenets** [RocketRobz/TWiLightMenu-Updater#5]
The TWLoader had the box arts downloader feature. I think should be a good idea to add that feature into the DSiMenuPlusPlus cause the source-code for it already exist.

I don't know how difficult this would be.

**Comment by Robz8** [comment]
DSiMenu++ reads box art in .bmp format, though.

**Comment by thenets** [comment]
@Robz8 I can create a webservice that converts it. What do you think?

**Comment by Robz8** [comment]
Here's box arts already converted: http://www.mediafire.com/file/3tsx99ylqi2840m/Dsimenu++%20ROM%20Covers.rar (credit to XrayXout)
Maybe maintain a server with these?

**Comment by thenets** [comment]
@Robz8 done :)
https://ds-covers.thenets.org/game/

**Comment by d0k3** [comment]
Seconding that request.

**Comment by MarioMasta64** [comment]
actually "https://art.gametdb.com/ds/coverDS/<region_code>/<titleid>.bmp" @Robz8 yea they do, just replace .png

**Comment by MarioMasta64** [comment]
they uploaded these for all the titles specifically for our downloaders purposes, so we dont have to download mid-quality boxart and convert it, they did all that for us with the hq boxart being the one converted

**Comment by d0k3** [comment]
(that guy again)

As far as I'm concerned, providing a single archive with all the boxarts is a fully acceptable solution. The archive isn't too big, and it's a one time affair, so it's fine. It should be hosted somewhere where it doesn't get lost, tho. One click hosters like MediaFire will delete the download after some time.

There may still be some missing, too, so there is room for improvement. PNG support in DSiMenu++ would be nice, cause it would shrink the archives' size. Shouldn't be too hard to do with lodePNG, which is also used by GM9.

**Comment by DMSalesman** [comment]
Last time I checked the boxart package, it contained covers for USA games only. I second a download facility that gets only the required covers from GameTDB.

**Comment by FlameKat53** [comment]
Epicpkmn11 is working on getting boxarts to download right now, he said he’s having trouble getting it to read the Title IDs

**Comment by Epicpkmn11** [comment]
As of #34 this is now implemented.
