### ISSUE TITLE
Rocketrobz this is urgent!

### ISSUE THREAD

**Issue by dearmrrobbs** [RocketRobz/TWiLightMenu-Updater#55]
I just booted up twilight menu updater updated twilight menu++ and nds bootstrap on my 3ds, and after I did that twilight updater crashed and reboot my 3ds and when it came back on all my 3ds games are missing! Twilight menu++ shows up but when I try to run it, all I get is a white screen of death. Please help. When I get to 3ds settings data management my games still show up but not on the home menu. This sucks much!

**Comment by Stack3r** [comment]
Close one of these issues, there’s no need to have two of the same thing.

**Comment by RocketRobz** [comment]
Sorry, no idea how to fix this. :(
Though to fix the white screen issue in TWLMenu++, delete `settings.ini` at `sd:/_nds/TWiLightMenu`.
