### ISSUE TITLE
Updater in 3dsx updates to cia

### ISSUE THREAD

**Issue by eku** [RocketRobz/TWiLightMenu-Updater#58]
I'm using the 3dsx version of the updater. When updating itself, it downloads and installs the cia version. Pretty annoying.

**Comment by SuperSaiyajinVoltZ** [comment]
Why not use the Cia Version of it? I mean, there is no Risk of getting Banned or something while using the Updater.

**Comment by NightYoshi370** [comment]
That's unrelated VoltZ. The user is allowed to use whatever format he wishes to use, and there's a bug with the 3DSX version of it.

He came here to report the bug of the 3DSX version, not to look for suggestions on what to use.

**Comment by Epicpkmn11** [comment]
Oh, yeah, this was fixed by #60

**Comment by eku** [comment]
@Epicpkmn11 the fix from #60 does not work for me. If updated with nightly builds, it still downloads and installs the CIA version.

**Comment by SuperSaiyajinVoltZ** [comment]
You Need `TWiLightMenu-Updater.3dsx` in `SD:/3ds`, then it download the `.3dsx`. If the file doesn't exists, then it download and installs the cia file.

**Comment by eku** [comment]
Why does the format decision depend on a file on the SD card? The currently running updater should know best whether it is a 3DSX or CIA version and download only the same version.

By the way, the homebrew is on ```SD:/3dsx/<name>/<name>.3dsx```.

**Comment by SuperSaiyajinVoltZ** [comment]
`(access("sdmc:/3ds/TWiLightMenu-Updater.3dsx", F_OK) != 0)) {`

This means, if this file is found, it does this Function. So when the File is not in this Location, it Downloads the CIA File.

**Comment by eku** [comment]
@SuperSaiyajinVoltZ so the code is no solution for this issue, because it requires conditions that are rarely met.
