### ISSUE TITLE
This updater has broke my TWLMenu++

### ISSUE THREAD

**Issue by with4** [RocketRobz/TWiLightMenu-Updater#61]
After install TWLMenu release using latest updater version, my 3ds gives me this message "An error has occurred. Press and hold the POWER Button to turn the system off. Please refer to the Operations Manual for details."

Deleting 3ds, dsiware, _nds folder, BOOT.nds and re-installing doesn't work. What should I do?

**Comment by RocketRobz** [comment]
Install the CIAs to SysNAND.

**Comment by with4** [comment]
> Install the CIAs to SysNAND.

It works! Sorry for bothering you. close.
