### ISSUE TITLE
Crash when selecting Updater Nightly

### ISSUE THREAD

**Issue by Filo97** [RocketRobz/TWiLightMenu-Updater#74]
System Information:
Model: New 3DS XL
Language: English
Region: EUR
Firmware: 11.10.0-43E
Luma: Luma 9.1
Crash dump: 
[crash_dump_00000001.zip](https://github.com/RocketRobz/TWiLightMenu-Updater/files/3349631/crash_dump_00000001.zip)

**Comment by NightYoshi370** [comment]
The updater is going through a major rewrite, so of course it'll break.
Please wait until we're done the rewrite, then try using the nightly version

**Comment by SuperSaiyajinVoltZ** [comment]
This is a Github API Issue, if you do a few Requests to the API, it blocks you for a bit of time. The only Thing you could do is : Wait a few minutes and don't do anything, which Requests something from Github's API.

**Comment by RocketRobz** [comment]
Doesn't seem to happen in later versions.
