### ISSUE TITLE
3.1.2 crashes instantly

### ISSUE THREAD

**Issue by kforney** [RocketRobz/TWiLightMenu-Updater#75]
3.1.2 ran once, when the app restarted itself during the upgrade, and was able to update TWiLightMenu++ and ndsbootrap, but after I attempted to download a theme ("dark", I believe), the app crashed.  It now crashes immediately at launch, and either crashes with a dump, or with the message "An error has occurred, forcing the software to close.  The system will now restart. (Unsaved data may be lost.)"

My crash dump is attached.
[crash_dump_00000004.dmp.gz](https://github.com/RocketRobz/TWiLightMenu-Updater/files/3349693/crash_dump_00000004.dmp.gz)

**Comment by SuperSaiyajinVoltZ** [comment]
This is because of Github's API Blocking. If you do a few of Requests, it blocks you for a bit of time. The only Thing you could do is : Wait a few minutes and don't do anything, which Requests something from Github's API.

**Comment by DMSalesman** [comment]
Are you sure it's a matter of requests? I fired up the updater exactly once to update to v9.0.0, successfully.

Today, I tried to launch it twice and it instantly crashed at startup.

**Comment by RocketRobz** [comment]
Doesn't seem to happen in later versions.
