### ISSUE TITLE
Twilight Menu++ is not being installed

### ISSUE THREAD

**Issue by semecan** [RocketRobz/TWiLightMenu-Updater#78]
I installed version 3.1.2 of the updater and tried to download Twilight Menu++ with it.
The updater downloads the release and says "done!" afterwards, but no title is being installed.

When checking the SD card, a Zip file with the latest release of Twilight Menu exists in the root of the card.

**Comment by Epicpkmn11** [comment]
If @RocketRobz switches the 7z on the TWiLight release to the one in this zip (GitHub doesn't allow `7z`s) it *should* be fixed. (I didn't test but usually the ones I make with p7zip work)
[TWiLightMenu.7z.zip](https://github.com/RocketRobz/TWiLightMenu-Updater/files/3492489/TWiLightMenu.7z.zip)

**Comment by semecan** [comment]
The same seems to apply to the nds-bootstrap releases too:
After manually installing twilight menu without copying nds-bootstrap and installing nds-bootstrap via the updater, twilight menu tells me no nds-bootstrap was found.

**Comment by RocketRobz** [comment]
Doesn't seem to happen in later versions.
