### ISSUE TITLE
FEATURE REQUEST: Downgrade versions

### ISSUE THREAD

**Issue by Pokefanmati** [RocketRobz/TWiLightMenu-Updater#86]
So, I know this may seem useless because who would like to go across older versions... well, me...
You see, there are a couple games that work better in older versions. For example (canonical example) Ninokuni crashes in the lastest version while ussing curative magic out of battle. Of course i just made a downgrade and everything if fine.
To be honest  I'm not sure if some could use this, but... i loose nothing by posting it here.

**Comment by RocketRobz** [comment]
Ni no Kuni works fine in the latest version of nds-bootstrap.
Use [this](https://mega.nz/#!7L4ETILL!yguPzZpB4PvVk5qU2JFm1X5MoWbKQrH9bqUHU-1hQ9M) patch.
