### ISSUE TITLE
The Updater Cashes while Installing TWL Menu Update

### ISSUE THREAD

**Issue by Foxxify1** [RocketRobz/TWiLightMenu-Updater#93]
**Model:**

old 2ds

**SysNAND Ver:**
(latest)
11.13.43-U

**Entrypoint:**
(latest)
B9S

**Luma 3ds Ver:**
(latest)
10.0.1

The updater downloads all of the files and extracts them. Then it goes to install the TWiLight Menu.cia file and crashes. Can anyone help?

[crash_dump_00000005.zip](https://github.com/RocketRobz/TWiLightMenu-Updater/files/4123608/crash_dump_00000005.zip)

**Comment by RocketRobz** [comment]
Doesn't seem to happen in later versions.
