### ISSUE TITLE
Updater crashes immediately

### ISSUE THREAD

**Issue by lowendpower** [RocketRobz/TWiLightMenu-Updater#96]
v4.0.0 states that the bug of "crashing when wifi is disabled" is fixed, but it still persists.

On New 3DS XL the Updater crashes the system when wifi is disabled. (I can't enable wifi since it hardcrashes the entire system.) So, the updater crashes when launched immediately. 

Tried both the .cia and .3dsx versions. Both had the exact same issue.

Attached the crashdump in case it helps solve the issue.
[crash_dump_00000001.zip](https://github.com/RocketRobz/TWiLightMenu-Updater/files/4216088/crash_dump_00000001.zip)

**Comment by RocketRobz** [comment]
Try other software that uses WiFi, and see if it crashes in them as well.

**Comment by lowendpower** [comment]
I am using several other apps like Anemone, FBI, Homebrew Launcher and emulators.
They all work fine without wifi, no crashes.

**Comment by RinMaru** [comment]
yea this happens. a workaround is dont launch it so quickly and let the wifi connect.

**Comment by Surax98** [comment]
I can give you another feedback: crashes with no Wi-Fi on my new 3ds xl. Do you need a crash dump?

**Comment by SuperSaiyajinStackZ** [comment]
I was pretty sure I fixed it for the startup crash. I have no clue why it still crashes for some People, for me it works perfectly fine even without WiFi.

**Comment by RoJoJoey** [comment]
Can confirm - Crashes upon startup. Other wifi-related applications run fine. Crashes on 3ds. Sys 11.13.0-45E. Installed on a freshly homebrewed (and tested) 3ds (not a 'new 3ds')
[crash_dump_00000000.zip](https://github.com/RocketRobz/TWiLightMenu-Updater/files/4329697/crash_dump_00000000.zip)
 Attatched is the crash dump.

**Comment by RocketRobz** [comment]
Fixed in v4.2.0.
